#!/usr/bin/python
import os
import json

os.system(
    "../flatpak-builder-tools/pip/flatpak-pip-generator "
    "--ignore-pkg pygobject "
    "-o python3-discover-overlay "
    "discover-overlay"
)

obj = {}
with open("python3-discover-overlay.json") as f:
    obj = json.load(f)

for source in obj["sources"]:
    if "PyGObject" in source["url"]:
        obj["sources"].remove(source)

with open("python3-discover-overlay.json", "w") as f:
    json.dump(obj, f, indent=4)
